package william_martinez_proyecto2_q3;

import java.awt.Dimension;

public class PgBusqueda_Twit_Hashtag extends javax.swing.JPanel {

    Pagina_Inicial pgInicial;
    
    public PgBusqueda_Twit_Hashtag(Pagina_Inicial pgInicial) {
        initComponents();
        this.pgInicial=pgInicial;
        setPreferredSize(new Dimension(770, 560));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
