/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package william_martinez_proyecto2_q3;

import java.awt.Dimension;
import java.awt.event.ActionEvent;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;


public class pgPerfil_Usuario extends javax.swing.JFrame {

    Pagina_Inicial pgInicial;
    private Followers followers;
    private Following following;
    private DefaultListModel<String>tweetModel;
    private String String;
    private String usernameFollower;
    
    public pgPerfil_Usuario(Pagina_Inicial pgInicial) {
        initComponents();
        setPreferredSize(new Dimension(770, 560));
         this.pgInicial = pgInicial;
        this.followers = new Followers();  // Crear instancia de Followers
        this.following = new Following();  // Crear instancia de Following
        this.tweetModel = new DefaultListModel<>();
        
       
        updateCounts();  // Actualizar contadores iniciales
        
        String generoStr = Character.toString(pgInicial.loggedUser.getLoggedUser().getGeneroUser());
        nombre.setText(pgInicial.loggedUser.getLoggedUser().getNombreUser());
        username.setText(pgInicial.loggedUser.getLoggedUser().getUsername());
        edad.setText(Integer.toString(pgInicial.loggedUser.getLoggedUser().getEdadUser()));
        genero.setText(generoStr);
        fechaIngreso.setText(pgInicial.loggedUser.getLoggedUser().getFechaHoraFormateada());
        tweetfield.setText(pgInicial.manejoUser.mostrarTwits(pgInicial.loggedUser.getLoggedUser().getUsername()));
    }
    
      private void updateCounts() {
        followerscount.setText(String.valueOf(followers.getFollowersCount()));
        followingcount.setText(String.valueOf(following.getFollowingCount()));
        tweetcount.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackHome = new javax.swing.JPanel();
        Backhomebtt = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nameTxt = new javax.swing.JLabel();
        usernameTxt = new javax.swing.JLabel();
        ageTxt = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        editbotton = new javax.swing.JButton();
        followingcount = new java.awt.TextField();
        followerscount = new java.awt.TextField();
        tweetcount = new java.awt.TextField();
        Followbutton = new javax.swing.JButton();
        generoTxt = new javax.swing.JLabel();
        fechaIngresoTxt = new javax.swing.JLabel();
        fechaIngreso = new java.awt.TextField();
        nombre = new java.awt.TextField();
        username = new java.awt.TextField();
        edad = new java.awt.TextField();
        genero = new java.awt.TextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tweetfield = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BackHome.setBackground(new java.awt.Color(198, 198, 252));
        BackHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Backhomebtt.setBackground(new java.awt.Color(153, 51, 255));
        Backhomebtt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Backhomebtt.setForeground(new java.awt.Color(51, 0, 0));
        Backhomebtt.setText("Home");
        Backhomebtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackhomebttActionPerformed(evt);
            }
        });
        BackHome.add(Backhomebtt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 20));
        BackHome.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, -1, -1));
        BackHome.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, -1, -1));

        nameTxt.setText("Nombre:");
        BackHome.add(nameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        usernameTxt.setText("UserN:");
        BackHome.add(usernameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        ageTxt.setText("Edad:");
        BackHome.add(ageTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel6.setText("Tweet's");
        BackHome.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, -1, -1));

        jLabel7.setText("Seguidores:");
        BackHome.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, -1, -1));

        jLabel8.setText("Siguiendo:");
        BackHome.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, -1, -1));

        editbotton.setBackground(new java.awt.Color(204, 204, 204));
        editbotton.setText("Editar");
        editbotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editbottonActionPerformed(evt);
            }
        });
        BackHome.add(editbotton, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, -1, 16));

        followingcount.setBackground(new java.awt.Color(204, 204, 255));
        followingcount.setName(""); // NOI18N
        followingcount.setText("textField1");
        followingcount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                followingcountActionPerformed(evt);
            }
        });
        BackHome.add(followingcount, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, 20, -1));

        followerscount.setBackground(new java.awt.Color(204, 204, 255));
        followerscount.setName(""); // NOI18N
        followerscount.setText("textField1");
        followerscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                followerscountActionPerformed(evt);
            }
        });
        BackHome.add(followerscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 20, -1));

        tweetcount.setBackground(new java.awt.Color(204, 204, 255));
        tweetcount.setName(""); // NOI18N
        tweetcount.setText("textField1");
        tweetcount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tweetcountActionPerformed(evt);
            }
        });
        BackHome.add(tweetcount, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 20, -1));

        Followbutton.setText("Seguir");
        Followbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FollowbuttonActionPerformed(evt);
            }
        });
        BackHome.add(Followbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 100, 20));

        generoTxt.setText("Genero: ");
        BackHome.add(generoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        fechaIngresoTxt.setText("Fecha de ingreso: ");
        BackHome.add(fechaIngresoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        fechaIngreso.setBackground(new java.awt.Color(204, 204, 255));
        fechaIngreso.setName(""); // NOI18N
        fechaIngreso.setText("textField1");
        fechaIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaIngresoActionPerformed(evt);
            }
        });
        BackHome.add(fechaIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 90, 20));

        nombre.setBackground(new java.awt.Color(204, 204, 255));
        nombre.setName(""); // NOI18N
        nombre.setText("textField1");
        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });
        BackHome.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 90, 20));

        username.setBackground(new java.awt.Color(204, 204, 255));
        username.setName(""); // NOI18N
        username.setText("textField1");
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        BackHome.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 90, 20));

        edad.setBackground(new java.awt.Color(204, 204, 255));
        edad.setName(""); // NOI18N
        edad.setText("textField1");
        edad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edadActionPerformed(evt);
            }
        });
        BackHome.add(edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 90, 20));

        genero.setBackground(new java.awt.Color(204, 204, 255));
        genero.setName(""); // NOI18N
        genero.setText("textField1");
        genero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generoActionPerformed(evt);
            }
        });
        BackHome.add(genero, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 90, 20));

        tweetfield.setColumns(20);
        tweetfield.setRows(5);
        jScrollPane4.setViewportView(tweetfield);

        BackHome.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 570, 290));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BackHome, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BackHome, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackhomebttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackhomebttActionPerformed
        // TODO add your handling code here:
        Pagina_Multiple pgMultiple = new Pagina_Multiple(pgInicial);
        pgMultiple.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BackhomebttActionPerformed

    private void editbottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editbottonActionPerformed
        // TODO add your handling code here:
        String nuevoNombre = JOptionPane.showInputDialog(this, "Ingrese su nuevo nombre:", nameTxt.getText());
        String nuevoUsername = JOptionPane.showInputDialog(this, "Ingrese su nuevo nombre de usuario:", usernameTxt.getText());
        String nuevaEdad = JOptionPane.showInputDialog(this, "Ingrese su nueva edad:", ageTxt.getText());

        // Validar que los campos no estén vacíos
        if (nuevoNombre != null && !nuevoNombre.trim().isEmpty()) {
            nameTxt.setText(nuevoNombre);
        }

        if (nuevoUsername != null && !nuevoUsername.trim().isEmpty()) {
            usernameTxt.setText(nuevoUsername);
        }

        if (nuevaEdad != null && !nuevaEdad.trim().isEmpty()) {
            try {
                int edad = Integer.parseInt(nuevaEdad);
                ageTxt.setText(String.valueOf(edad));
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Edad no válida, por favor ingrese un número.");
            }
        }
    }//GEN-LAST:event_editbottonActionPerformed

    private void followingcountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_followingcountActionPerformed
        // TODO add your handling code here:
        // Supongamos que tienes un objeto de perfil de usuario con el número de seguidores
        String[] followingtotal = following.getFollowingList(); // Método que obtienes de tu modelo
        JOptionPane.showMessageDialog(this, "Número de cuentas que sigues: " +followingtotal);
        followingcount.setText(String.valueOf(following.getFollowingCount()));
    }//GEN-LAST:event_followingcountActionPerformed

    private void followerscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_followerscountActionPerformed
        // TODO add your handling code here:
        // Supongamos que tienes un objeto de perfil de usuario con el número de seguidores
        int followersCount = followers.getFollowersCount(); // Método que obtienes de tu modelo
        JOptionPane.showMessageDialog(this, "Número de seguidores: " + followersCount);
        followerscount.setText(String.valueOf(followers.getFollowersCount()));
    }//GEN-LAST:event_followerscountActionPerformed

    private void tweetcountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tweetcountActionPerformed
        // TODO add your handling code here:
        tweetcount.setText(String.valueOf(tweetModel.size()));
    }//GEN-LAST:event_tweetcountActionPerformed

    private void FollowbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FollowbuttonActionPerformed
        // TODO add your handling code here:
        // Obtén el nombre de usuario a seguir
        String usernameToFollow = usernameFollower;  // Asegúrate de obtener el valor correctamente

        if (usernameToFollow.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "El nombre de usuario no puede estar vacío.");
            return;
        }

        // Aquí deberías tener un método en tu modelo para seguir a un usuario
        boolean success = followers.followUser(usernameToFollow);

        if (success) {
            JOptionPane.showMessageDialog(this, "Ahora sigues a " + usernameToFollow);
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo seguir a " + usernameToFollow);
        }
    }//GEN-LAST:event_FollowbuttonActionPerformed

    private void fechaIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaIngresoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaIngresoActionPerformed

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void edadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edadActionPerformed

    private void generoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_generoActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackHome;
    private javax.swing.JButton Backhomebtt;
    private javax.swing.JButton Followbutton;
    private javax.swing.JLabel ageTxt;
    private java.awt.TextField edad;
    private javax.swing.JButton editbotton;
    private java.awt.TextField fechaIngreso;
    private javax.swing.JLabel fechaIngresoTxt;
    private java.awt.TextField followerscount;
    private java.awt.TextField followingcount;
    private java.awt.TextField genero;
    private javax.swing.JLabel generoTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel nameTxt;
    private java.awt.TextField nombre;
    private java.awt.TextField tweetcount;
    private javax.swing.JTextArea tweetfield;
    private java.awt.TextField username;
    private javax.swing.JLabel usernameTxt;
    // End of variables declaration//GEN-END:variables
}
