/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package william_martinez_proyecto2_q3;

import java.awt.Dimension;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author DELL
 */
public class PgPerfil_Usuario extends javax.swing.JFrame {

    Pagina_Inicial pgInicial;
    private Followers followers;
    private Following following;
    private DefaultListModel<String> tweetModel;
    private String String;
    private String usernameFollower;
    
    public PgPerfil_Usuario(Pagina_Inicial pgInicial) {
        initComponents();
        setPreferredSize(new Dimension(770, 560));
        this.followers = new Followers();  // Crear instancia de Followers
        this.following = new Following();  // Crear instancia de Following
        this.tweetModel = new DefaultListModel<>();
        this.pgInicial = pgInicial;
        
        System.out.println("Esta");
        updateCounts();  // Actualizar contadores iniciales
        
        String nombreUser = pgInicial.loggedUser.getLoggedUser().getNombreUser();
        
        tweetfield.setText(pgInicial.manejoUser.mostrarTwits(nombreUser));
    }
    
      private void updateCounts() {
        followerscount.setText(String.valueOf(followers.getFollowersCount()));
        followingcount.setText(String.valueOf(following.getFollowingCount()));
        tweetcount.setText(String.valueOf(tweetModel.size()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        BackHome = new javax.swing.JPanel();
        Backhomebtt = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        Username = new javax.swing.JLabel();
        Age = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        editbotton = new javax.swing.JButton();
        followingcount = new java.awt.TextField();
        followerscount = new java.awt.TextField();
        tweetcount = new java.awt.TextField();
        tweetfield = new javax.swing.JTextField();
        Followbutton = new javax.swing.JButton();
        tweetcount1 = new java.awt.TextField();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BackHome.setBackground(new java.awt.Color(198, 198, 252));
        BackHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Backhomebtt.setBackground(new java.awt.Color(153, 51, 255));
        Backhomebtt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Backhomebtt.setForeground(new java.awt.Color(51, 0, 0));
        Backhomebtt.setText("Home");
        Backhomebtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackhomebttActionPerformed(evt);
            }
        });
        BackHome.add(Backhomebtt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 20));
        BackHome.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, -1, -1));
        BackHome.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, -1, -1));

        name.setText("Nombre:");
        BackHome.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        Username.setText("Username:");
        BackHome.add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        Age.setText("Edad:");
        BackHome.add(Age, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel6.setText("Tweet's");
        BackHome.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, -1, -1));

        jLabel7.setText("Seguidores:");
        BackHome.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, -1, -1));

        jLabel8.setText("Siguiendo:");
        BackHome.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, -1, -1));

        editbotton.setBackground(new java.awt.Color(204, 204, 204));
        editbotton.setText("Editar");
        editbotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editbottonActionPerformed(evt);
            }
        });
        BackHome.add(editbotton, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, -1, 16));

        followingcount.setBackground(new java.awt.Color(204, 204, 255));
        followingcount.setEditable(false);
        followingcount.setName(""); // NOI18N
        followingcount.setText("textField1");
        followingcount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                followingcountActionPerformed(evt);
            }
        });
        BackHome.add(followingcount, new org.netbeans.lib.awtextra.AbsoluteConstraints(526, 70, 30, -1));

        followerscount.setBackground(new java.awt.Color(204, 204, 255));
        followerscount.setEditable(false);
        followerscount.setName(""); // NOI18N
        followerscount.setText("textField1");
        followerscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                followerscountActionPerformed(evt);
            }
        });
        BackHome.add(followerscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(426, 70, 30, -1));

        tweetcount.setBackground(new java.awt.Color(204, 204, 255));
        tweetcount.setEditable(false);
        tweetcount.setName(""); // NOI18N
        tweetcount.setText("textField1");
        tweetcount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tweetcountActionPerformed(evt);
            }
        });
        BackHome.add(tweetcount, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 30, -1));

        tweetfield.setBackground(new java.awt.Color(217, 204, 252));
        tweetfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tweetfieldActionPerformed(evt);
            }
        });
        BackHome.add(tweetfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 214, 580, 240));

        Followbutton.setText("Seguir");
        Followbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FollowbuttonActionPerformed(evt);
            }
        });
        BackHome.add(Followbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 100, 20));

        tweetcount1.setBackground(new java.awt.Color(204, 204, 255));
        tweetcount1.setEditable(false);
        tweetcount1.setName(""); // NOI18N
        tweetcount1.setText("textField1");
        tweetcount1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tweetcount1ActionPerformed(evt);
            }
        });
        BackHome.add(tweetcount1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 80, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(BackHome, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(BackHome, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackhomebttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackhomebttActionPerformed
        // TODO add your handling code here:
//        Pagina_Multiple parentFrame = (Pagina_Multiple) SwingUtilities.getWindowAncestor(this);
//        parentFrame.mostrarPantalla("Pagina-Inicial");
        Pagina_Multiple pgMultiple = new Pagina_Multiple(pgInicial);
        pgMultiple.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BackhomebttActionPerformed

    private void editbottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editbottonActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_editbottonActionPerformed

    private void followingcountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_followingcountActionPerformed
        // TODO add your handling code here:
        // Supongamos que tienes un objeto de perfil de usuario con el número de seguidores
        String[] followingtotal = following.getFollowingList(); // Método que obtienes de tu modelo
        JOptionPane.showMessageDialog(this, "Número de cuentas que sigues: " +followingtotal);
    }//GEN-LAST:event_followingcountActionPerformed

    private void followerscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_followerscountActionPerformed
        // TODO add your handling code here:
        // Supongamos que tienes un objeto de perfil de usuario con el número de seguidores
        int followersCount = followers.getFollowersCount(); // Método que obtienes de tu modelo
        JOptionPane.showMessageDialog(this, "Número de seguidores: " + followersCount);
    }//GEN-LAST:event_followerscountActionPerformed

    private void tweetcountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tweetcountActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_tweetcountActionPerformed

    private void tweetfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tweetfieldActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_tweetfieldActionPerformed

    private void FollowbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FollowbuttonActionPerformed
        // TODO add your handling code here:
        // Obtén el nombre de usuario a seguir
        String usernameToFollow = Followers.getText();

        if (usernameToFollow.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "El nombre de usuario no puede estar vacío.");
            return;
        }

        // Aquí deberías tener un método en tu modelo para seguir a un usuario
        boolean success = User_info.Followers(usernameFollower);

        if (success) {
            JOptionPane.showMessageDialog(this, "Ahora sigues a " + usernameToFollow);
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo seguir a " + usernameToFollow);
        }
    }//GEN-LAST:event_FollowbuttonActionPerformed

    private void tweetcount1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tweetcount1ActionPerformed
        
    }//GEN-LAST:event_tweetcount1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Age;
    private javax.swing.JPanel BackHome;
    private javax.swing.JButton Backhomebtt;
    private javax.swing.JButton Followbutton;
    private javax.swing.JLabel Username;
    private javax.swing.JButton editbotton;
    private java.awt.TextField followerscount;
    private java.awt.TextField followingcount;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel name;
    private java.awt.TextField tweetcount;
    private java.awt.TextField tweetcount1;
    private javax.swing.JTextField tweetfield;
    // End of variables declaration//GEN-END:variables
}
